### ISSUE TITLE
Including Framework dependencies

### ISSUE THREAD

**Issue by c-h-** [axemclion/react-native-cordova-plugin#26] opened 2016-05-03 21:17 UTC
I had to include a dependency in the build.gradle file at `framework/android/build.gradle` like so to get push notification support working.

`compile 'com.google.android.gms:play-services-gcm:8.4.0'`

The issue I was having was that compilation was failing because a plugin I'm using adds the following line in AndroidManifest.xml in manifest/application:

``` xml
<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
```

Do you know of a better way to do this that doesn't require modifying this package's build.gradle? I could not figure out how to add it to the React Native project's build.gradle in a way that it would be available during compilation.

**Comment by axemclion** [comment] 2016-05-03 21:25
@c-h- Is there a link to the plugin you are using ? If this works with Cordova, it should technically work with ReactNative too, unless there is a bug. 

In case of this adapter, we have an additional AndroidManifest.xml that is merged with the project's manifest.

**Comment by c-h-** [comment] 2016-05-03 22:28
Yea the plugin is here: https://github.com/UpChannel/pushwoosh-phonegap-plugin

The XML is in plugin.xml: https://github.com/UpChannel/pushwoosh-phonegap-plugin/blob/master/plugin.xml

I'm not sure if it's a bug or not, but without modifying the build.gradle of react-native-cordova-plugin, compilation would fail saying that `@integer/google_play_services_version` was not available. Including the line in build.gradle makes it available.

I hope that makes some sense - I'm a bit out of my comfort zone when it comes to gradle.

**Comment by axemclion** [comment] 2016-05-03 23:35
@c-h- I was able to reproduce the error. Looks like the `framework` element in the plugin.xml is not getting  picked up. 

Here is how Cordova is supposed to deal with it - https://github.com/apache/cordova-lib/blob/9f630271d9c02824c0031ea4cdc0e4955b53d9e2/cordova-lib/src/plugman/platforms/android.js#L117

**Comment by axemclion** [comment] 2016-05-04 00:56
More analysis, and looks like this is something that Cordova does. For each of those dependencies, it has a `project.properties`. These are then moved to the appropriate gradle files using [a prepBuild](https://github.com/apache/cordova-android/blob/master/bin/templates/cordova/lib/builders/GradleBuilder.js#L67) step.

I would need to implement this, for the plugin to be supported.

**Comment by axemclion** [comment] 2016-05-04 05:10
This almost works, except for [this issue](https://github.com/Pushwoosh/pushwoosh-phonegap-plugin/issues/176). 

Once the plugin fixes the issue - i.e. removes the custom gradle file, you should be able to use it. To test for now, you could look for `node_modules/react-native-cordova-plugin/platforms/android/pushwoosh-cordova-plugin/*.gradle` and make that an empty file. Once the pushwoosh bug is fixed, you will no longer need this hack, and your code should continue working.

**Comment by c-h-** [comment] 2016-05-04 19:30
Awesome!! Thanks for all the support. I'll comment back with my results.

**Comment by c-h-** [comment] 2016-05-06 03:25
@axemclion Installing straight from github URL so I can use the framework support you added in your last commit, I could not get a project to build. I should mention that this test was _not_ in a fresh React Native project, it was in a pretty complex project. But the only change I made was uninstalling the npm version of this package and then installing via git url.

This is the error I was getting:

``` bash
[23:14:52] Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
[23:14:52] 
java.lang.IllegalStateException: buildToolsVersion is not specified.
    at com.google.common.base.Preconditions.checkState(Preconditions.java:176)
    at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:599)
    at com.android.build.gradle.BasePlugin$10$1.call(BasePlugin.java:566)
    at com.android.build.gradle.BasePlugin$10$1.call(BasePlugin.java:563)
    at com.android.builder.profile.ThreadRecorder$1.record(ThreadRecorder.java:55)
```

To get it to build, I commented out this line of `build.gradle` that you added in 8942fb03bf8e60d50caa76ed79aa56c785f5799a 
`// apply from: "$projectDir/../../platforms/android/plugin-build.gradle"`

**Comment by axemclion** [comment] 2016-05-06 16:05
This could be due to the fact that I not not cleaning the older version. The issue here was possibly that the frameworks were already present from the previous build.

Could you delete the `node_modules/react-native-cordova-plugin/platforms` directory and then add your git URL ? will that work ?

**Comment by axemclion** [comment] 2016-05-08 01:06
Closing this issue since there is no more work for this specific issue. 
If there is an issue with deleting and adding a plugin again, we should open another issue.

**Closed as completed by axemclion** 2016-05-08 01:06 UTC
