### ISSUE TITLE
[question][need help] module cordova/plugin_list not found

### ISSUE THREAD

**Issue by benedyktdryl** [axemclion/react-native-cordova-plugin#31] opened 2016-05-12 20:21 UTC
I'm doing everything like you described it in readme. After all I'm getting error described in title:

`module cordova/plugin_list not found`

Can you point me if I'm doing something wrong? 
I'm using:
- latest OSX
- latest package version you provided
- this project as starter, with no changes at all: https://github.com/jhabdas/react-native-webpack-starter-kit
- also I'm using NPM 3.8.6 with Node 5.11.0

I also follow your instructions, went through them few times.
I'm really sorry if it's something stupid I missed.

Thanks for your time.

**Comment by axemclion** [comment] 2016-05-16 16:51
@cypherq Can you also share your project somewhere? Maybe easier to start building from there. I see that the starter project in the link above does not include the plugin. How are you including the plugin ?

**Comment by axemclion** [comment] 2016-07-04 21:07
This question has been around for a while, and I was not able to reproduce it. Closing this now. Please re-open if you are still having trouble.

**Closed as completed by axemclion** 2016-07-04 21:07 UTC
Labels: question

**Comment by mint3000** [comment] 2016-07-08 20:54
I ran into this issue as well, it happened after I ran `node_modules/.bin/cordova-plugin clean`, I tried running 'node_modules/.bin/cordova-plugin repair' but that produced this error: 

```
An error occured ===> 
 { [Error: ENOENT: no such file or directory, open '/Users/ryanh/REPOS/cm-living-portraits-rn/node_modules/react-native-cordova-plugin/platforms/android/assets/www/cordova.js']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/ryanh/REPOS/cm-living-portraits-rn/node_modules/react-native-cordova-plugin/platforms/android/assets/www/cordova.js' }
```

So I ran `node_modules/.bin/cordova-plugin add cordova` which produces an error but it also re-creates the `platform` directory. 

But to get assets/www/cordova.js and the plugin_list I had to re-add my plugins. So in my instance I ran `node_modules/.bin/cordova-plugin add https://github.com/petermetz/cordova-plugin-ibeacon.git`

Hopefully this helps anyone else who ran into these issues.
