### ISSUE TITLE
cordovaplugin:processReleaseResources FAILED while running `react-native run-android`

### ISSUE THREAD

**Issue by yorzi** [axemclion/react-native-cordova-plugin#29] opened 2016-05-10 07:31 UTC
Could you give me some hint on below issue? I am using latest ReactNative and add cordava-plugin according to the guide in readme. Thanks.

```
:cordovaplugin:processReleaseResources
/Users/andy/workspace/vego.projects/VegoMobile/node_modules/react-native-cordova-plugin/framework/android/build/intermediates/bundles/release/aapt/AndroidManifest.xml:20:28-65 : No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

:cordovaplugin:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cordovaplugin:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/local/opt/android-sdk/build-tools/23.0.1/aapt'' finished with non-zero exit value 1

```

**Comment by axemclion** [comment] 2016-05-10 15:26
@yorzi What plugin are you using this with ? This looks like a an error similar to #26, but that should be resolved.

**Comment by yorzi** [comment] 2016-05-11 03:04
@axemclion I did try to follow #26 's instruction, but failed to resolve my problem. I am going to use a plugin called [cordova-plugin-connectsdk](http://www.svlconnectsdk.com/docs/1-6-0/cordova/setup-instructions/). I also tried `cordova-plugin-contacts` and it did work gracefully. Thanks for your reply.

**Comment by yorzi** [comment] 2016-05-11 03:37
Actually, when I add `compile 'com.google.android.gms:play-services-gcm:8.4.0'` to the `framework/android/build.gradle` file as described in #26 , I can pass the issue, but I encountered new problems like below:

```
/Users/andy/workspace/vego.projects/VegoMobile/node_modules/react-native-cordova-plugin/platforms/android/src/com/connectsdk/cordova/ConnectableDeviceWrapper.java:33: error: package com.connectsdk.device does not exist
import com.connectsdk.device.ConnectableDevice;
```

I am not sure if it's something wrong with connectsdk plugin or it's something wrong caused by my modification on `react-native-cordova-plugin`, I am new to android dev..

Really appreciate your hints.

**Comment by axemclion** [comment] 2016-05-11 04:39
@yorzi Looks like there is a bug in this project in [this line](https://github.com/axemclion/react-native-cordova-plugin/blob/76d08110e9cead0b4e9cfb979566d3d3c41a7322/cli/android-cli.js#L117) when trying to add the plugin that you mention. I will have to use Cordova's [GradleBuilder](https://github.com/apache/cordova-android/blob/ef268e23206f3378d5c8c5dd279d2821830766b2/bin/templates/cordova/lib/builders/GradleBuilder.js) to ensure that this runs.

**Comment by yorzi** [comment] 2016-05-11 07:52
@axemclion I fixed the compilation issue by adding below lines to `framework/android/build.gradle`

```
    compile 'com.google.android.gms:play-services-cast:8.4.0'
    compile 'com.google.android.gms:play-services-gcm:8.4.0'
    compile 'com.connectsdk:connect-sdk-android:1.6.0'
```

However, I am not able to do `import cordova from 'react-native-cordova-plugin';` in my index.android.js file, and it throws `ConnectSDK is not defined` which I guess is not loaded correctly from the plugin adapter. Do you know why it happens like this? Thanks in advance!

<img width="345" alt="screen shot 2016-05-11 at 3 49 49 pm" src="https://cloud.githubusercontent.com/assets/38976/15173711/423548d8-1790-11e6-9502-b6dd0868e713.png">

**Comment by axemclion** [comment] 2016-05-11 16:00
Will look at this over the weekend.

**Comment by yorzi** [comment] 2016-05-13 07:57
@axemclion Thanks, hope connectSDK plugin can work well with this adapter as expected.

**Comment by yorzi** [comment] 2016-05-15 14:31
Hi @axemclion any luck to find anything related to this issue? Thanks!!

**Comment by axemclion** [comment] 2016-05-16 17:02
@yorzi Can you try running `node_modules/.bin/cordova-plugin repair` to generate the cordova.js file ? That should have the SDK, if it is in `node_modules/react-native-cordova-plugin/platforms/android/assets/www/cordova_plugin.js`

**Comment by axemclion** [comment] 2016-07-04 21:08
Thanks for the bug; Closing this as I am not able to reproduce it. Please re-open if you still have this issue.

**Closed as completed by axemclion** 2016-07-04 21:08 UTC
