### ISSUE TITLE
Undefined is not an object

### ISSUE THREAD

**Issue by FSpierckel** [axemclion/react-native-cordova-plugin#4] opened 2015-10-23 13:20 UTC
Hello,

first thank you for your job, it's amazing to use cordova plugin directly in React !

I followed your tutorial and I'm able to use the barcodescanner.

But now, I'm trying to use de sqlite plugin : https://github.com/litehelpers/Cordova-sqlite-storage

I added the plugin but when I try to use it I have this error : undefined is not an objet (evaluating 'cordova.window.sqlitePlugin').

This is my piece of code : 

var cordova = require('react-native-cordova-plugin');
class Database {
   openDb() {
     cordova.window.sqlitePlugin.openDatabase({name: "my.db", location: 2});
   }
}

Thanks in advance,
Florian

**Comment by axemclion** [comment] 2015-10-23 15:26
Note that this should not be `cordova.window.sqlitePlugin`. From the plugin, looks like the object is used as `sqlitePlugin.openDatabase` - meaning that the object is exposed on  `window` object in Cordova. Hence, while using it in reactNative, it will be available as `cordova.sqlitePlugin.openDatabase`.

**Comment by FSpierckel** [comment] 2015-10-23 15:31
I tried it but still getting the same error..  "undefined is not an object (evalutating cordova.sqlitePlugin.openDatabase)"

**Comment by axemclion** [comment] 2015-10-23 16:07
Looks like the case is incorrect - it seems to be called `SQLitePlugin`, so it would be used as `cordova.SQLitePlugin`

**Comment by Spierki** [comment] 2015-10-23 18:02
I saw that it's write like that in the plugin file too so I tried it but it gives me the same error. 
Is it working for you ? 
"undefined is not an object (evalutating cordova.SQLitePlugin.openDatabase)"

I also tried to remove/import again the plugin

**Comment by FSpierckel** [comment] 2015-10-23 18:13
I saw that it's write like that in the plugin file too so I tried it and It's a little bit better, now in the error message I can find the parameter that I passed on the function call : "undefined is not an object (evalutating cordova.SQLitePlugin.openDatabase({name:"my.db",location:1})"

I also tried to call another function but I'm get the same kind of message

**Comment by axemclion** [comment] 2015-10-23 18:17
Do you have a sample app that I could try ?

**Comment by FSpierckel** [comment] 2015-10-23 19:54
I just wrote a very little example. https://github.com/Spierki/ReactNative-SQlite-Example

**Comment by nikkool** [comment] 2015-11-12 19:11
I can't seem to figure out how to pass a function call. I've been trying to use the camera plugin and tried many ways, 4 of which are as follows.

```
    if (source ==='Camera') {
        cordova.navigator.camera.getPicture(this.itWorked, (msg) => {this.itFailed(msg);},
           {sourceType : cordova.navigator.camera.PictureSourceType.CAMERA,
            encodingType: cordova.navigator.camera.EncodingType.JPEG,  targetWidth: 1280,  targetHeight: 720,
            destinationType: cordova.navigator.camera.DestinationType.DATA_URL})


    } else { /*use photoLibrary*/
      cordova.navigator.camera.getPicture((x) => {console.log(x);}, function (result) {console.log("Result: " + result);},
           {sourceType : cordova.navigator.camera.PictureSourceType.PHOTOLIBRARY,
             mediaType: cordova.navigator.camera.MediaType.PICTURE,
             destinationType: cordova.navigator.camera.DestinationType.DATA_URL})
    }
```

Can you point out what I'm doing wrong?

further I've defined itWorked and itFailed as functions, but they don't seem to get called:

```
  itWorked :   function(imageData: string){
      this.setState({imageData:imageData})
 },

  itFailed:  function(error: string){
    this.setState({error:error})

  },
```

**Comment by axemclion** [comment] 2015-11-12 21:48
@nikkool 
Do you have your full snippet that I can take a look at ? Also, i think it may make sense to open new bug for this.

**Comment by FSpierckel** [comment] 2015-11-13 08:48
@axemclion did you tried my code ?

**Comment by axemclion** [comment] 2015-11-14 22:20
@Spierki I looked at your code and figured out what the issue is. Note that I am using the latest version of the sqlite plugin, and react-native-cordova-plugin@0.0.7

This issue is that the SQlitePlugin does not export [the object](https://github.com/litehelpers/Cordova-sqlite-storage/blob/96915dfa1ba323b6bbcf117416f42a706d71fb60/www/SQLitePlugin.js#L566). It simply assigns it to `this` in [this line](https://github.com/litehelpers/Cordova-sqlite-storage/blob/96915dfa1ba323b6bbcf117416f42a706d71fb60/www/SQLitePlugin.js#L4). While `this` refers to `window` in a cordova app and works perfectly fine, `window` does not exist in ReactNative. Hence, you do not have a handle to that object.

A way to fix it would be to modify the SQLitePlugin [here](https://github.com/litehelpers/Cordova-sqlite-storage/blob/96915dfa1ba323b6bbcf117416f42a706d71fb60/www/SQLitePlugin.js#L566) and add a line that says `module.exports=root.sqlitePlugin`. We could send in a pull request to the plugin, since exporting is the right way to do it.

**Comment by axemclion** [comment] 2015-11-14 22:27
I plan to close this issue in a couple of days. If you are not able to get it working, please respond to this thread, and we can look to see if there are other issues.

**Comment by brody2consult** [comment] 2015-11-17 00:13
For sqlite, I recommend that you use https://github.com/andpor/react-native-sqlite-storage. I cannot promise when litehelpers/Cordova-sqlite-storage#382 will be fixed. @axemclion I recommend that you close this since the functionality is already supported by [andpor / react-native-sqlite-storage](https://github.com/andpor/react-native-sqlite-storage).

**Comment by axemclion** [comment] 2015-11-17 00:23
@brodybits Sounds good - thanks. Closing this issue.

**Closed as completed by axemclion** 2015-11-17 00:23 UTC

**Comment by FSpierckel** [comment] 2015-11-17 08:08
@axemclion I tried what you said and it's working thank you ! @brodybits The plugin you said looks like to be functionnal, thanks too.
